jobs:
 - name: u16
   type: runSh
   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16"
             imageTag: master
         script:
            - java -version
            - nodejs --version
            - yarn -version
            - source /usr/local/rvm/scripts/rvm
            - ruby -v
            - python -V
            - pip --version
            - virtualenv --version
            - git --version
            - aws --version
            - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - git lfs version
            - kubectl version --client
            - kops version
            - helm version --client
            - doctl version
            - ansible --version
            - pip show boto
            - pip show boto3
            - pip show apache-libcloud
            - pip show azure
            - pip show dopy
            - packer --version
            - jq --version
            - terraform --version
            - openstack --version
          
       
 - name: u16all
   type: runSh
   steps:
     - IN: u16
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16all"
             imageTag: master
         script:
            - shippable_service cassandra start
            - shippable_service cassandra stop
            - shippable_service couchdb start
            - shippable_service couchdb stop
            - shippable_service elasticsearch start
            - shippable_service elasticsearch stop
            - shippable_service memcached start
            - shippable_service memcached stop
            - shippable_service mongodb start
            - shippable_service mongodb stop
            - shippable_service mysql start
            - shippable_service mysql stop
            - shippable_service neo4j start
            - shippable_service neo4j stop
            - shippable_service postgres start
            - shippable_service postgres stop
            - shippable_service rabbitmq start
            - shippable_service rabbitmq stop
            - shippable_service redis start
            - shippable_service redis stop
            - shippable_service riak start
            - shippable_service riak stop
            - shippable_service selenium start
            - shippable_service selenium stop
            - psql --version
            - java -jar /usr/local/selenium/selenium-server-standalone-3.11.0.jar --version
            - sqlite3 --version
            - mysql --version
            - elasticsearch --version
            - memcached --version
            - riak version
            - sudo -i -u couchdb /opt/couchdb/bin/couchdb 2>&1 >/dev/null &
            - sleep 5
            - curl http://127.0.0.1:5984/
            - dpkg -s rabbitmq-server | grep  Version
            - redis-server --version
            - mongod --version
            - cassandra -v  
            - /var/lib/neo4j/bin/neo4j version

- name: u16nodall
   type: runSh
   steps:
     - IN: u16all
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16nodall"
             imageTag: master
           script:
           - ls
           
- name: u16pytall
   type: runSh
   steps:
     - IN: u16all
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16pytall"
             imageTag: master
           script:
           - ls

- name: u16javall
   type: runSh
   steps:
     - IN: u16all
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16javall"
             imageTag: master
           script:
           - ls
           
 - name: u16cppall
   type: runSh
   steps:
     - IN: u16all
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16cppall"
             imageTag: master
           script:
           - ls
           
                      
 - name: u16golall
   type: runSh
   steps:
     - IN: u16all
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16golall"
             imageTag: master
           script:
           - ls
           
 - name: u16phpall
   type: runSh
   steps:
     - IN: u16all
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16phpall"
             imageTag: master
           script:
           - ls
           
 - name: u16cloall
   type: runSh
   steps:
     - IN: u16all
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16cloall"
             imageTag: master
           script:
           - ls
           
 - name: u16ruball
   type: runSh
   steps:
     - IN: u16all
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16ruball"
             imageTag: master
           script:
           - ls
           
 - name: u16scaall
   type: runSh
   steps:
     - IN: u16all
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16scaall"
             imageTag: master
           script:
           - ls
            
          
