jobs:
 - name: u16
   type: runSh
   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16"
             imageTag: master
         script:
            - java -version
            - nodejs --version
            - yarn -version
            - source /usr/local/rvm/scripts/rvm
            - ruby -v
            - python -V
            - pip --version
            - virtualenv --version
            - git --version
            - aws --version
            - eb --version
            - az --version
            - jfrog --version
            - gcloud version
            - git lfs version
            - kubectl version --client
            - helm version --client
            - doctl version
            - ansible --version
            - pip show boto
            - pip show boto3
            - pip show apache-libcloud
            - pip show azure
            - pip show dopy
            - packer --version
            - jq --version
            - terraform --version
            - openstack --version
            - npm --version
            - kops version
          
       
 - name: u16all
   type: runSh
   steps:
     - IN: u16
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16all"
             imageTag: master
         script:
            #- shippable_service cassandra start
            #- shippable_service cassandra stop
            - shippable_service couchdb start
            - shippable_service couchdb stop
            - shippable_service elasticsearch start
            - shippable_service elasticsearch stop
            - shippable_service memcached start
            - shippable_service memcached stop
            - shippable_service mongodb start
            - shippable_service mongodb stop
            - shippable_service mysql start
            - shippable_service mysql stop
            - shippable_service neo4j start
            - shippable_service neo4j stop
            - shippable_service postgres start
            - shippable_service postgres stop
            - shippable_service rabbitmq start
            - shippable_service rabbitmq stop
            - shippable_service redis start
            - shippable_service redis stop
            - shippable_service riak start
            - shippable_service riak stop
            - shippable_service selenium start
            - shippable_service selenium stop
            - psql --version
            - java -jar /usr/local/selenium/selenium-server-standalone-3.14.0.jar --version
            - sqlite3 --version
            - mysql --version
            - elasticsearch --version
            - memcached --version
            - riak version
            - sudo -i -u couchdb /opt/couchdb/bin/couchdb 2>&1 >/dev/null &
            - sleep 5
            - curl http://127.0.0.1:5984/
            - dpkg -s rabbitmq-server | grep  Version
            - redis-server --version
            - mongod --version
           # - cassandra -v  
            - /var/lib/neo4j/bin/neo4j version
            - pip show pycrypto 
            
 - name: servicesCIu16all_runCI
   type: runCI
   steps:
     - IN: servicesCIu16all_ciRepo
     - IN: u16all
    
 - name: pipelineu16nodall_runCI
   type: runCI
   steps:
     - IN: pipelineu16nodall_ciRepo
     - IN: servicesCIu16all_runCI

 - name: pipelineu16javall_runCI
   type: runCI
   steps:
     - IN: pipelineu16javall_ciRepo
     - IN: servicesCIu16all_runCI

 - name: pipelineu16cppall_runCI
   type: runCI
   steps:
     - IN: pipelineu16cppall_ciRepo
     - IN: servicesCIu16all_runCI

 - name: pipelineu16php_runCI
   type: runCI
   steps:
     - IN: pipelineu16php_ciRepo
     - IN: servicesCIu16all_runCI

 - name: pipelineu16pytall_runCI
   type: runCI
   steps:
     - IN: pipelineu16pytall_ciRepo
     - IN: servicesCIu16all_runCI
     
     
 - name: pipelineu16scaall_runCI
   type: runCI
   steps:
    - IN: pipelineu16scaall_ciRepo
    - IN: servicesCIu16all_runCI
    
 - name: pipelineu16ruball_runCI
   type: runCI
   steps:
    - IN: pipelineu16ruball_ciRepo
    - IN: servicesCIu16all_runCI
    
 - name: pipelineu16cloall_runCI
   type: runCI
   steps:
     - IN: pipelineu16cloall_ciRepo
     - IN: servicesCIu16all_runCI
 
 - name: pipelineu16golall_runCI
   type: runCI
   steps:
   - IN: pipelineu16golall_ciRepo
   - IN: servicesCIu16all_runCI
